#!/usr/bin/env python3
"""
Text to Python Conversion
Generated: 2026-07-21T14:32:57.842Z
Total Lines: 317
"""

def process_text():
    """
    Process and analyze text data
    Returns: dictionary with text data and metadata
    """
    text_lines = [
    "\"\"\"",
    "STRATEGY 3 — Crypto Confluence System (BTC + ETH)",
    "5-lock system: HTF trend (4H) + PDH/PDL liquidity zone (+ OI/funding context",
    "as a free proxy for the paid Coinglass heatmap) + Asian range sweep +",
    "MSS/FVG confirmation (1M) + news/risk filters.",
    "Data source: Binance public API (free, no key required).",
    "Crypto trades 24/7 — unlike forex, weekends are NOT skipped here.",
    "LIMITATIONS:",
    "- No programmatic access to the real Coinglass liquidation heatmap (paid",
    "  only). We approximate with PDH/PDL + funding rate + open interest, and",
    "  send you a direct link to glance at the real heatmap before entering.",
    "- MSS/FVG uses closed 1m candles only.",
    "\"\"\"",
    "import os",
    "import json",
    "import random",
    "import requests",
    "import pandas as pd",
    "from datetime import datetime, timedelta, timezone",
    "from zoneinfo import ZoneInfo",
    "TELEGRAM_TOKEN   = os.environ[\"TELEGRAM_BOT_TOKEN\"]",
    "TELEGRAM_CHAT_ID = os.environ[\"TELEGRAM_CHAT_ID\"]",
    "SYMBOLS = {\"BTC\": \"BTCUSDT\", \"ETH\": \"ETHUSDT\"}",
    "STATE_FILE = \"crypto_state.json\"",
    "ASIAN_START_H, ASIAN_END_H = 0, 6",
    "LONDON_START_H, LONDON_END_H = 7, 10",
    "LATE_CUTOFF_H = 11",
    "SWEEP_MIN_PCT   = 0.001   # 0.1% beyond range = real sweep",
    "SL_BUFFER_PCT   = 0.0015  # 0.15% buffer beyond sweep extreme",
    "PDH_PDL_TOLERANCE_PCT = 0.005  # sweep must land within 0.5% of PDH/PDL to count as confluence",
    "RISK_REWARD     = 3.0",
    "BE_TRIGGER_RR   = 1.5",
    "FVG_MAX_MINUTES = 15",
    "ENTRY_EXPIRY_MINUTES = 10",
    "US_DATA_WINDOW = (\"08:20\", \"09:10\")",
    "FOMC_WINDOW    = (\"13:55\", \"14:50\")",
    "STATUS_MINUTE_INTERVAL = 30",
    "OFFDUTY_LINES = [",
    "    \"😴 برا أوقات صيدي الحين، الكريبتو يتداول 24/7 بس أنا أراقب بنافذة محددة بس.\",",
    "    \"🌙 نايم شوي عن الفحص المكثف، بس السوق نفسه مفتوح دايمًا.\",",
    "    \"☕ استراحة من جهتي، بس تابعني قريب أرجع أشتغل.\",",
    "]",
    "FUN_EMOJIS = [\"🕵️\", \"🔎\", \"🧭\", \"🛰️\", \"📡\", \"🌊\", \"💎\"]",
    "GREEN_EMOJIS = [\"🟢\", \"✅\", \"🚀\"]",
    "# ============================================================",
    "# BINANCE DATA (free, public, no API key)",
    "# ============================================================",
    "def fetch_klines(symbol, interval, limit):",
    "    url = \"https://api.binance.com/api/v3/klines\"",
    "    r = requests.get(url, params={\"symbol\": symbol, \"interval\": interval, \"limit\": limit}, timeout=30)",
    "    raw = r.json()",
    "    df = pd.DataFrame(raw, columns=[",
    "        \"open_time\", \"open\", \"high\", \"low\", \"close\", \"volume\", \"close_time\",",
    "        \"qav\", \"trades\", \"tb_base\", \"tb_quote\", \"ignore\"])",
    "    df[\"datetime\"] = pd.to_datetime(df[\"open_time\"], unit=\"ms\", utc=True)",
    "    for col in [\"open\", \"high\", \"low\", \"close\"]:",
    "        df[col] = df[col].astype(float)",
    "    return df[[\"datetime\", \"open\", \"high\", \"low\", \"close\"]]",
    "def fetch_funding_rate(symbol):",
    "    try:",
    "        url = \"https://fapi.binance.com/fapi/v1/fundingRate\"",
    "        r = requests.get(url, params={\"symbol\": symbol, \"limit\": 1}, timeout=15)",
    "        return float(r.json()[0][\"fundingRate\"]) * 100  # as %",
    "    except Exception:",
    "        return None",
    "def fetch_open_interest(symbol):",
    "    try:",
    "        url = \"https://fapi.binance.com/fapi/v1/openInterest\"",
    "        r = requests.get(url, params={\"symbol\": symbol}, timeout=15)",
    "        return float(r.json()[\"openInterest\"])",
    "    except Exception:",
    "        return None",
    "def fetch_long_short_ratio(symbol):",
    "    try:",
    "        url = \"https://fapi.binance.com/futures/data/globalLongShortAccountRatio\"",
    "        r = requests.get(url, params={\"symbol\": symbol, \"period\": \"1h\", \"limit\": 1}, timeout=15)",
    "        return float(r.json()[0][\"longShortRatio\"])",
    "    except Exception:",
    "        return None",
    "def coinglass_link(coin):",
    "    return f\"https://www.coinglass.com/pro/futures/LiquidationHeatMap?coin={coin}\"",
    "# ============================================================",
    "# HTF TREND (4H)",
    "# ============================================================",
    "def htf_bias(symbol):",
    "    df = fetch_klines(symbol, \"4h\", 250)",
    "    df[\"ema50\"] = df[\"close\"].ewm(span=50, adjust=False).mean()",
    "    df[\"ema200\"] = df[\"close\"].ewm(span=200, adjust=False).mean()",
    "    last = df.iloc[-1]",
    "    if last[\"close\"] > last[\"ema50\"] > last[\"ema200\"]:",
    "        return \"up\"",
    "    elif last[\"close\"] < last[\"ema50\"] < last[\"ema200\"]:",
    "        return \"down\"",
    "    return \"range\"",
    "def prev_day_high_low(symbol):",
    "    df = fetch_klines(symbol, \"1d\", 3)",
    "    prev = df.iloc[-2]  # last fully closed day",
    "    return float(prev[\"high\"]), float(prev[\"low\"])",
    "# ============================================================",
    "# NEWS BLACKOUT",
    "# ============================================================",
    "def in_news_blackout():",
    "    now_et = datetime.now(ZoneInfo(\"America/New_York\"))",
    "    hm = now_et.strftime(\"%H:%M\")",
    "    return US_DATA_WINDOW[0] <= hm <= US_DATA_WINDOW[1] or FOMC_WINDOW[0] <= hm <= FOMC_WINDOW[1]",
    "# ============================================================",
    "# TELEGRAM",
    "# ============================================================",
    "def send_telegram(coin, message):",
    "    url = f\"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage\"",
    "    full_msg = f\"[STRATEGY 3 - Crypto | {coin}] \" + random.choice(FUN_EMOJIS) + \"\\n\" + message",
    "    requests.post(url, data={\"chat_id\": TELEGRAM_CHAT_ID, \"text\": full_msg}, timeout=15)",
    "# ============================================================",
    "# STATE",
    "# ============================================================",
    "def load_all_state():",
    "    if os.path.exists(STATE_FILE):",
    "        with open(STATE_FILE) as f:",
    "            return json.load(f)",
    "    return {}",
    "def save_all_state(state):",
    "    with open(STATE_FILE, \"w\") as f:",
    "        json.dump(state, f, default=str)",
    "def fresh_daily_state(today_str):",
    "    return {",
    "        \"date\": today_str, \"asian_high\": None, \"asian_low\": None, \"sweep\": None,",
    "        \"pending_signal\": None, \"trade_taken_today\": False,",
    "        \"asian_start_sent\": False, \"london_start_sent\": False, \"closing_soon_sent\": False,",
    "        \"last_status_minute_block\": None, \"last_offduty_hour\": None,",
    "    }",
    "# ============================================================",
    "# SWING / MSS / FVG",
    "# ============================================================",
    "def find_last_swing(df1m, direction):",
    "    n = len(df1m)",
    "    for i in range(n - 3, 1, -1):",
    "        if direction == \"high\":",
    "            if (df1m[\"high\"][i] > df1m[\"high\"][i - 1] and df1m[\"high\"][i] > df1m[\"high\"][i - 2]",
    "                    and df1m[\"high\"][i] > df1m[\"high\"][i + 1] and df1m[\"high\"][i] > df1m[\"high\"][i + 2]):",
    "                return df1m[\"high\"][i]",
    "        else:",
    "            if (df1m[\"low\"][i] < df1m[\"low\"][i - 1] and df1m[\"low\"][i] < df1m[\"low\"][i - 2]",
    "                    and df1m[\"low\"][i] < df1m[\"low\"][i + 1] and df1m[\"low\"][i] < df1m[\"low\"][i + 2]):",
    "                return df1m[\"low\"][i]",
    "    return None",
    "def check_mss_and_fvg(df1m, sweep_type):",
    "    if len(df1m) < 6:",
    "        return False, None",
    "    last = df1m.iloc[-1]",
    "    if sweep_type == \"sell\":",
    "        sw = find_last_swing(df1m.iloc[:-1].reset_index(drop=True), \"low\")",
    "        if sw is None or last[\"close\"] >= sw:",
    "            return False, None",
    "        c1, c3 = df1m.iloc[-3], df1m.iloc[-1]",
    "        return (True, c1[\"low\"]) if c1[\"low\"] > c3[\"high\"] else (False, None)",
    "    else:",
    "        sw = find_last_swing(df1m.iloc[:-1].reset_index(drop=True), \"high\")",
    "        if sw is None or last[\"close\"] <= sw:",
    "            return False, None",
    "        c1, c3 = df1m.iloc[-3], df1m.iloc[-1]",
    "        return (True, c1[\"high\"]) if c1[\"high\"] < c3[\"low\"] else (False, None)",
    "# ============================================================",
    "# PER-SYMBOL LOGIC",
    "# ============================================================",
    "def process_symbol(coin, binance_symbol, state):",
    "    now_utc = datetime.now(timezone.utc)",
    "    today_str = now_utc.strftime(\"%Y-%m-%d\")",
    "    hour, minute = now_utc.hour, now_utc.minute",
    "    if state.get(\"date\") != today_str:",
    "        state = fresh_daily_state(today_str)",
    "    # --- off-duty hourly personality check-in ---",
    "    if hour >= LATE_CUTOFF_H:",
    "        if state.get(\"last_offduty_hour\") != hour:",
    "            recap = \"✅ أخذنا صفقة اليوم\" if state.get(\"trade_taken_today\") else \"🤷 ما صارت صفقة اليوم\"",
    "            hrs_left = 24 - hour",
    "            send_telegram(coin, f\"{random.choice(OFFDUTY_LINES)}\\n{recap}. أرجع أشتغل خلال {hrs_left} ساعة تقريبًا ⏰\")",
    "            state[\"last_offduty_hour\"] = hour",
    "        return state",
    "    if hour == ASIAN_START_H and not state.get(\"asian_start_sent\"):",
    "        send_telegram(coin, \"🌏 بدأت جلسة آسيا! برسم نطاق السعر لين الساعة 6 صباحًا UTC 📐\")",
    "        state[\"asian_start_sent\"] = True",
    "    if hour == LONDON_START_H and minute < 15 and not state.get(\"london_start_sent\"):",
    "        ah, al = state.get(\"asian_high\"), state.get(\"asian_low\")",
    "        range_txt = f\"النطاق: {al:,.2f} - {ah:,.2f} 📏\" if ah and al else \"النطاق لسا ما تحدد ⚠️\"",
    "        send_telegram(coin, f\"🇬🇧🔥 بدأت نافذة الصيد! ندور على اصطياد سيولة يلتقي مع PDH/PDL\\n{range_txt}\")",
    "        state[\"london_start_sent\"] = True",
    "    if hour == LATE_CUTOFF_H - 1 and minute >= 30 and not state.get(\"closing_soon_sent\"):",
    "        pend = \"فيه صفقة معلقة 👀\" if state.get(\"pending_signal\") else \"لين الحين ما فيه شي 🤏\"",
    "        send_telegram(coin, f\"⏰ باقي حوالي 30 دقيقة على إغلاق نافذة الدخول اليوم! {pend}\")",
    "        state[\"closing_soon_sent\"] = True",
    "    if LONDON_START_H <= hour < LATE_CUTOFF_H:",
    "        minute_block = (hour * 60 + minute) // STATUS_MINUTE_INTERVAL",
    "        if state.get(\"last_status_minute_block\") != minute_block:",
    "            if state.get(\"pending_signal\") and state[\"pending_signal\"][\"status\"] == \"pending\":",
    "                status_txt = f\"🎯 فيه أمر معلق عند {state['pending_signal']['entry']:,.2f}\"",
    "            elif state.get(\"sweep\"):",
    "                status_txt = f\"🌊 اصطياد سيولة ({state['sweep']['type']})، نستنى MSS+FVG\"",
    "            elif state.get(\"trade_taken_today\"):",
    "                status_txt = \"✅ خلصنا صفقة اليوم\"",
    "            else:",
    "                status_txt = f\"{random.choice(FUN_EMOJIS)} نراقب، ما فيه اصطياد واضح لين الحين\"",
    "            send_telegram(coin, f\"📡 تحديث دوري: {status_txt}\")",
    "            state[\"last_status_minute_block\"] = minute_block",
    "    # --- Phase 1: Asian range ---",
    "    if ASIAN_START_H <= hour <= ASIAN_END_H:",
    "        df15 = fetch_klines(binance_symbol, \"15m\", 60)",
    "        today_asia = df15[(df15[\"datetime\"].dt.date.astype(str) == today_str)",
    "                           & (df15[\"datetime\"].dt.hour >= ASIAN_START_H)",
    "                           & (df15[\"datetime\"].dt.hour < ASIAN_END_H)]",
    "        if len(today_asia) > 0:",
    "            state[\"asian_high\"] = float(today_asia[\"high\"].max())",
    "            state[\"asian_low\"] = float(today_asia[\"low\"].min())",
    "        return state",
    "    if hour < LONDON_START_H:",
    "        return state",
    "    if state.get(\"trade_taken_today\"):",
    "        return state",
    "    if state.get(\"asian_high\") is None:",
    "        return state",
    "    # --- Phase 2: monitor pending signal ---",
    "    pending = state.get(\"pending_signal\")",
    "    if pending and pending.get(\"status\") == \"pending\":",
    "        expires = datetime.fromisoformat(pending[\"expires\"])",
    "        df1m = fetch_klines(binance_symbol, \"1m\", 15)",
    "        touched = ((pending[\"direction\"] == \"sell\" and df1m[\"high\"].max() >= pending[\"entry\"])",
    "                   or (pending[\"direction\"] == \"buy\" and df1m[\"low\"].min() <= pending[\"entry\"]))",
    "        if touched:",
    "            pending[\"status\"] = \"filled\"",
    "            state[\"trade_taken_today\"] = True",
    "            send_telegram(coin,",
    "                f\"{random.choice(GREEN_EMOJIS)} ENTRY TRIGGERED — {pending['direction'].upper()} 🎉\\n\"",
    "                f\"Entry: {pending['entry']:,.2f}\\nStop Loss: {pending['sl']:,.2f} 🛑\\n\"",
    "                f\"Take Profit: {pending['tp']:,.2f} 🎯\\n\"",
    "                f\"حرك الوقف للتعادل عند 1:{BE_TRIGGER_RR} 🔒\\n\"",
    "                f\"شيك الخريطة الحرارية قبل التنفيذ: {coinglass_link(coin)}\")",
    "            return state",
    "        if now_utc >= expires:",
    "            pending[\"status\"] = \"expired\"",
    "            state[\"pending_signal\"] = pending",
    "            send_telegram(coin, f\"⌛ انتهت صلاحية الأمر بدون تنفيذ ({pending['direction'].upper()} @ {pending['entry']:,.2f}) 🤷\")",
    "            return state",
    "        return state",
    "    # --- Phase 3: look for sweep + PDH/PDL confluence ---",
    "    sweep = state.get(\"sweep\")",
    "    if not sweep:",
    "        df15 = fetch_klines(binance_symbol, \"15m\", 10)",
    "        last15 = df15.iloc[-1]",
    "        pdh, pdl = prev_day_high_low(binance_symbol)",
    "        bias = htf_bias(binance_symbol)",
    "        sweep_up = last15[\"high\"] >= state[\"asian_high\"] * (1 + SWEEP_MIN_PCT)",
    "        sweep_down = last15[\"low\"] <= state[\"asian_low\"] * (1 - SWEEP_MIN_PCT)",
    "        near_pdh = abs(last15[\"high\"] - pdh) / pdh <= PDH_PDL_TOLERANCE_PCT",
    "        near_pdl = abs(last15[\"low\"] - pdl) / pdl <= PDH_PDL_TOLERANCE_PCT",
    "        candidate = None",
    "        if sweep_up and near_pdh and bias != \"up\":",
    "            candidate = {\"type\": \"sell\", \"time\": now_utc.isoformat(), \"extreme\": float(last15[\"high\"])}",
    "        elif sweep_down and near_pdl and bias != \"down\":",
    "            candidate = {\"type\": \"buy\", \"time\": now_utc.isoformat(), \"extreme\": float(last15[\"low\"])}",
    "        if candidate:",
    "            funding = fetch_funding_rate(binance_symbol)",
    "            oi = fetch_open_interest(binance_symbol)",
    "            ls_ratio = fetch_long_short_ratio(binance_symbol)",
    "            context = []",
    "            if funding is not None:",
    "                context.append(f\"Funding: {funding:.3f}%\")",
    "            if oi is not None:",
    "                context.append(f\"OI: {oi:,.0f}\")",
    "            if ls_ratio is not None:",
    "                context.append(f\"Long/Short: {ls_ratio:.2f}\")",
    "            context_txt = \" | \".join(context) if context else \"بيانات إضافية غير متاحة حاليًا\"",
    "            state[\"sweep\"] = candidate",
    "            send_telegram(coin,",
    "                f\"🌊🚨 اصطياد سيولة عند منطقة PDH/PDL! احتمال {candidate['type'].upper()}\\n\"",
    "                f\"اتجاه 4H: {bias}\\n{context_txt}\\n\"",
    "                f\"نراقب MSS + FVG خلال {FVG_MAX_MINUTES} دقيقة القادمة ⏱️\")",
    "        return state",
    "    sweep_time = datetime.fromisoformat(sweep[\"time\"])",
    "    if now_utc - sweep_time > timedelta(minutes=FVG_MAX_MINUTES):",
    "        state[\"sweep\"] = None",
    "        return state",
    "    if in_news_blackout():",
    "        return state",
    "    df1m = fetch_klines(binance_symbol, \"1m\", 15)",
    "    found, entry = check_mss_and_fvg(df1m, sweep[\"type\"])",
    "    if found:",
    "        if sweep[\"type\"] == \"sell\":",
    "            sl = sweep[\"extreme\"] * (1 + SL_BUFFER_PCT)",
    "            risk = sl - entry",
    "            tp = entry - risk * RISK_REWARD",
    "        else:",
    "            sl = sweep[\"extreme\"] * (1 - SL_BUFFER_PCT)",
    "            risk = entry - sl",
    "            tp = entry + risk * RISK_REWARD",
    "        pending_signal = {\"direction\": sweep[\"type\"], \"entry\": float(entry), \"sl\": float(sl), \"tp\": float(tp),",
    "                           \"created\": now_utc.isoformat(),",
    "                           \"expires\": (now_utc + timedelta(minutes=ENTRY_EXPIRY_MINUTES)).isoformat(),",
    "                           \"status\": \"pending\"}",
    "        state[\"pending_signal\"] = pending_signal",
    "        send_telegram(coin,",
    "            f\"{random.choice(GREEN_EMOJIS)} MSS + FVG CONFIRMED — {sweep['type'].upper()} جاهز 🔥\\n\"",
    "            f\"Pending Limit Entry: {entry:,.2f}\\nStop Loss: {sl:,.2f} 🛑\\n\"",
    "            f\"Take Profit (1:{RISK_REWARD:g}): {tp:,.2f} 🎯\\n\"",
    "            f\"ينتهي لو ما انلمس خلال {ENTRY_EXPIRY_MINUTES} دقايق ⏳\\n\"",
    "            f\"راجع الخريطة الحرارية: {coinglass_link(coin)}\")",
    "    return state",
    "# ============================================================",
    "# MAIN",
    "# ============================================================",
    "def main():",
    "    all_state = load_all_state()",
    "    for coin, binance_symbol in SYMBOLS.items():",
    "        symbol_state = all_state.get(coin, {})",
    "        symbol_state = process_symbol(coin, binance_symbol, symbol_state)",
    "        all_state[coin] = symbol_state",
    "    save_all_state(all_state)",
    "if __name__ == \"__main__\":",
    "    main()"
    ]
    
    # Calculate metadata
    metadata = {
        'total_lines': 317,
        'total_characters': 15662,
        'total_words': 1509,
        'created_at': '2026-07-21T14:32:57.843Z',
        'version': '1.0'
    }
    
    # Calculate statistics
    line_lengths = [len(line) for line in text_lines]
    statistics = {
        'average_line_length': sum(line_lengths) // len(line_lengths) if line_lengths else 0,
        'longest_line': max(line_lengths) if line_lengths else 0,
        'shortest_line': min(line_lengths) if line_lengths else 0,
        'empty_lines': 62
    }
    
    return {
        'lines': text_lines,
        'metadata': metadata,
        'statistics': statistics
    }

def display_text(data):
    """Display text data with metadata"""
    print("Metadata:")
    for key, value in data['metadata'].items():
        print(f"  {key}: {value}")
    
    print("\nStatistics:")
    for key, value in data['statistics'].items():
        print(f"  {key}: {value}")
    
    print("\nText Lines:")
    for i, line in enumerate(data['lines'], 1):
        print(f"Line {i}: {line}")

if __name__ == "__main__":
    data = process_text()
    display_text(data)